name: First Workflow
on:
  push:
    branches:
      - master
jobs:
  MiprimerJob:
    name: deploy a msg
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: actions/checkout@v3
    - name: mi primer mensaje
      run: echo "Hola mundo" >> hola.txt
